apiVersion: v1
kind: ServiceAccount
metadata:
  name: system
  namespace: openshift-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: openshift-monitoring
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: route-monitor-operator-system
      terminationGracePeriodSeconds: 10
