apiVersion: v1
kind: ServiceAccount
metadata:
  name: system
  namespace: openshift-monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: openshift-monitoring
  labels:
    control-plane: controller-manager
    app: route-monitor-operator
    component: operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app: route-monitor-operator
      component: operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        app: route-monitor-operator
        component: operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --metrics-addr=127.0.0.1:8080
        - --enable-leader-election
        - --zap-log-level=$(LOG_LEVEL)
        - --blackbox-image=$(BLACKBOX_IMAGE)
        env:
        - name: LOG_LEVEL
          # level 1 is debug, so when we want to raise the level we can
          value: "1"
        - name: BLACKBOX_IMAGE
          # override so you can pull any blackbox-exporter image you fancy
          # this value is the default value
          value: "quay.io/app-sre/prom-blackbox-exporter:master"
        image: controller:latest
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 20Mi
      serviceAccountName: route-monitor-operator-system
      terminationGracePeriodSeconds: 10
