---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rmo-pipelines
  namespace: ci

---
# tekton/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rmo-pipelines
  namespace: openshift-route-monitor-operator
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rmo-pipelines
  namespace: ci
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - triggers.tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - tekton.dev
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rmo-pipelines
rules:
- apiGroups:
  - '*'
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - monitoring.openshift.io
  resources:
  - clusterurlmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.openshift.io
  resources:
  - clusterurlmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.openshift.io
  resources:
  - routemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.openshift.io
  resources:
  - routemonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
---
# tekton/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rmo-pipelines
  namespace: ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rmo-pipelines
  namespace: ci
subjects:
- kind: ServiceAccount
  name: rmo-pipelines
  namespace: ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rmo-pipelines-rmo-ns
  namespace: openshift-route-monitor-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rmo-pipelines
  namespace: openshift-route-monitor-operator
subjects:
- kind: ServiceAccount
  name: rmo-pipelines
  namespace: ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rmo-pipelines-rmo-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rmo-pipelines
subjects:
- kind: ServiceAccount
  name: rmo-pipelines
  namespace: ci

