apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-oc
spec:
  workspaces:
  - name: oc
  steps:
    - name: test
      image: quay.io/bitnami/golang:1.14
      workingDir: /workspace/oc
      command: ["/bin/bash", "-c"]
      args:
        - |-
          git clone https://github.com/openshift/route-monitor-operator
          cd route-monitor-operator
          go test ./int
      resources:
        requests:
          memory: 1Gi
          cpu: 800m
        limits:
          memory: 1Gi
          cpu: 800m
