name: Make Generate
on: push

jobs:
  run:
    name: Make Generate Template
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Make
      run: make generate-syncsets

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "make generate-syncsets"
        add: "hack/olm-registry/olm-artifacts-template.yaml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
